### PR TITLE
Release 2.4.0

### PR DESCRIPTION
**Pull request by jankapunkt**
This merges the current dev state into `master`, making 2.4.0 the new main HEAD.

### CODE REVIEW

**Review by TheRealNate — APPROVED** [review]

**Comment by TheRealNate** [comment]
Seems like it will be a big help! Approved, LGTM.

**Comment by jankapunkt** [comment]
It's merged but I still can't publish to NPM registry, can you do that or add me to the ord on NPM (I have 2FA active on NPM)

**Comment by TheRealNate** [comment]
@jankapunkt sure can do, same username?

**Comment by jankapunkt** [comment]
@TheRealNate thanks I just got the invitation and will publish now

**Comment by jankapunkt** [comment]
Hm seems to be revoked, anyway my account is https://www.npmjs.com/~jkuester

**Comment by TheRealNate** [comment]
Added!

**Pull request merged**
