### PR TITLE
Fix/connection events

### PR DESCRIPTION
**Pull request by jankapunkt**
## Summary

In rare occasions I found that when using `NetInfo: null` in order to manually manage connect/disconnect, I can't get the App connected, due to the events being fired before the listeners were attached internally.

I therefore moved the code to call Data.dpp.connect at a point after the listeners were set up.
Should not break current builds.

## Reproduction

install `@meteorrn/core@2.8.1-rc.0` to test

### CODE REVIEW

**Comment by bratelefant** [comment]
Cool, will test this in my staging env; from time to time I also have a similar issue (might be related) where especially when the app is suspended in iOS and then brought back up, the current Meteor.user() is undefined.

**Comment by jankapunkt** [comment]
Can you please open an issue on the Meteor.user problem including a minimal repro code? I have some null user errors on my server and it might be related

**Comment by bratelefant** [comment]
> Can you please open an issue on the Meteor.user problem including a minimal repro code? I have some null user errors on my server and it might be related

Will try to, however this seems really hard to reproduce. Sometimes got `User._loginWithToken::: token is null` in the logs; There's no check [here in User.js](https://github.com/meteorrn/meteor-react-native/blob/fix/connection-events/src/user/User.js#L189), if the parameter value is not null. Anyway, this is off-topic with respect to this PR, so I'll file an issue and we can go on there

**Review by bratelefant — CHANGES_REQUESTED** [review]
Looks fine, works fine. For testing this (I'm using the "local collections" companion package) I needed to bump peerDependencies for that package; can you the version numbers of core to the peerDeps of the companion packages as well?

**Review by bratelefant — APPROVED** [review]

**Comment by jankapunkt** [comment]
Sorry reviews got dismissed after merge. I disabled that option for now. Can you please approve again?

**Review by bratelefant — APPROVED** [review]
Look good, think we could merge in #150 as well

**Pull request merged**
