### PR TITLE
Replaced wolfy87-eventemitter with core EventEmtiter from 'events'

### PR DESCRIPTION
**Pull request by jankapunkt**
implementes #112

### CODE REVIEW

**Review by TheRealNate — APPROVED** [review]
✅ LGTM

**Comment by TheRealNate** [comment]
@jankapunkt can you resolve merge conflicts, GitHub keeps giving me issues

**Comment by jankapunkt** [comment]
@TheRealNate yes I will look at them

**Comment by jankapunkt** [comment]
@TheRealNate resolved

**Review by TheRealNate — APPROVED** [review]

**Comment by jankapunkt** [comment]
Thanks @TheRealNate I will create a new release 2.5.0 and publish on NPM.

**Comment by juanpmd** [comment]
@jankapunkt does this change require installing the npm package events? I am having problems running meteorrn without it but wanted to make sure this is the correct way.

**Comment by jankapunkt** [comment]
Hey @juanpmd I investigated and it seems to be a mistake from my end here. The tests never catched this, since they run with node, which itself holds `events` but the React Native engine doesn't know about `events` and it's not possible to simply install them. The npm `events` package is also not an official core package and not maintained since two years. I'm thinking if finding a good solution here, maybe `eventemitter3`?

**Comment by jankapunkt** [comment]
@juanpmd can you please take a look at PR #129 and let me know if this works for your setup without the need for the `events` dependency?

**Pull request merged**
